# ==============================================================
# = GestUser - Servizio Gestione Utenti 
# ==============================================================

server:
  port: 8019
spring:
  application:
    name: GestUser
# ==============================================================
# = MONGODB Parameters
# ==============================================================
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: localhost
      password: password
      port: 37017
      username: user
